stages:
  - test
  - deploy

check-source-code-format:
  stage: test
  image: pommalabs/dotnet-mono:dotnet-3-mono-6-sdk
  script:
    - ./build.sh --target check-source-code-format

pages:
  stage: deploy
  image:
    name: pommalabs/doxygen
    entrypoint: [""]
  script:
    - PROJECT_NUMBER=$CI_COMMIT_SHA doxygen
    - mv artifacts/docs public
  artifacts:
    paths:
      - public
  only:
    - master
