stages:
  - test
  - publish
  - deploy

check-source-code-format:
  stage: test
  image: pommalabs/dotnet-mono:dotnet-3-mono-6-sdk
  script:
    - dotnet format --dry-run --check --verbosity diagnostic

publish-on-myget:
  stage: publish
  image: pommalabs/dotnet-mono:dotnet-3-mono-6-sdk
  script:
    - find src -name "*.csproj" -exec dotnet pack -c Release -o artifacts -p:Version=$CI_COMMIT_TAG -p:ContinuousIntegrationBuild=true {} \;
    - find artifacts -name "*.nupkg" -exec dotnet nuget push -k $MYGET_API_KEY {} \;
  artifacts:
    paths:
      - artifacts
    expire_in: 1 year
  only:
    - tags

pages:
  stage: deploy
  image:
    name: pommalabs/doxygen
    entrypoint: [""]
  script:
    - PROJECT_NUMBER=$CI_COMMIT_SHA doxygen
    - mv artifacts/docs public
  artifacts:
    paths:
      - public
  only:
    - master
