stages:
  - build
  - publish
  - deploy

build-solution:
  stage: build
  image: pommalabs/dotnet-mono:dotnet-3-mono-6-sdk
  script:
    - ./build.sh --target build-solution

publish-on-myget:
  stage: publish
  image: pommalabs/dotnet-mono:dotnet-3-mono-6-sdk
  script:
    - ./build.sh --target publish-on-myget
  artifacts:
    expire_in: 1 year
    paths:
      - ./artifacts/nuget-packages/*.nupkg
  only:
    - tags

pages:
  stage: deploy
  image:
    name: pommalabs/doxygen
    entrypoint: [""]
  script:
    - PROJECT_NUMBER=$CI_COMMIT_SHA doxygen
    - mv artifacts/docs public
  artifacts:
    paths:
      - public
  only:
    - master
