stages:
  - test
  - deploy

include:
  - project: pommalabs/templates
    file: /.gitlab/ci_templates/dotnet/deploy-doxygen-docs.gitlab-ci.yml

check-source-code-style:
  stage: test
  image: pommalabs/dotnet-mono:preview
  script:
    - ./build.sh --target check-source-code-style
